package cl.taisachile.scc.ws.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import cl.taisachile.scc.ws.AdministrationWS;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-07-13T16:03:56.578-04:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "AdministrationWSImplService", 
                  wsdlLocation = "file:/home/cavallinux/dev/src/sandbox/wsmocks/admin-wsserver/src/main/wsdl/AdministrationWS.wsdl",
                  targetNamespace = "http://impl.ws.scc.taisachile.cl/") 
public class AdministrationWSImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.scc.taisachile.cl/", "AdministrationWSImplService");
    public final static QName AdministrationWSImplPort = new QName("http://impl.ws.scc.taisachile.cl/", "AdministrationWSImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/cavallinux/dev/src/sandbox/wsmocks/admin-wsserver/src/main/wsdl/AdministrationWS.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AdministrationWSImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/cavallinux/dev/src/sandbox/wsmocks/admin-wsserver/src/main/wsdl/AdministrationWS.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AdministrationWSImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AdministrationWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdministrationWSImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns AdministrationWS
     */
    @WebEndpoint(name = "AdministrationWSImplPort")
    public AdministrationWS getAdministrationWSImplPort() {
        return super.getPort(AdministrationWSImplPort, AdministrationWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdministrationWS
     */
    @WebEndpoint(name = "AdministrationWSImplPort")
    public AdministrationWS getAdministrationWSImplPort(WebServiceFeature... features) {
        return super.getPort(AdministrationWSImplPort, AdministrationWS.class, features);
    }

}
