package com.falabella.mdwcorp.osb.wsdl.cmr.corp.satif.tarjeta.consultaridclientepan.consulta_v1_0;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-07-13T19:38:49.420-04:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "ConsultarIDClientePANService", 
                  wsdlLocation = "file:/home/cavallinux/dev/src/sandbox/wsmocks/panquery-wsserver/src/main/wsdl/wsdl/OSB_CMR_CORP_ConsultarIDClientePAN.wsdl",
                  targetNamespace = "http://mdwcorp.falabella.com/OSB/wsdl/CMR/CORP/Satif/tarjeta/consultarIDClientePAN/consulta-v1.0") 
public class ConsultarIDClientePANService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://mdwcorp.falabella.com/OSB/wsdl/CMR/CORP/Satif/tarjeta/consultarIDClientePAN/consulta-v1.0", "ConsultarIDClientePANService");
    public final static QName ConsultarIDClientePANPort = new QName("http://mdwcorp.falabella.com/OSB/wsdl/CMR/CORP/Satif/tarjeta/consultarIDClientePAN/consulta-v1.0", "ConsultarIDClientePANPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/cavallinux/dev/src/sandbox/wsmocks/panquery-wsserver/src/main/wsdl/wsdl/OSB_CMR_CORP_ConsultarIDClientePAN.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ConsultarIDClientePANService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/cavallinux/dev/src/sandbox/wsmocks/panquery-wsserver/src/main/wsdl/wsdl/OSB_CMR_CORP_ConsultarIDClientePAN.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ConsultarIDClientePANService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ConsultarIDClientePANService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultarIDClientePANService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ConsultarIDClientePANPt
     */
    @WebEndpoint(name = "ConsultarIDClientePANPort")
    public ConsultarIDClientePANPt getConsultarIDClientePANPort() {
        return super.getPort(ConsultarIDClientePANPort, ConsultarIDClientePANPt.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultarIDClientePANPt
     */
    @WebEndpoint(name = "ConsultarIDClientePANPort")
    public ConsultarIDClientePANPt getConsultarIDClientePANPort(WebServiceFeature... features) {
        return super.getPort(ConsultarIDClientePANPort, ConsultarIDClientePANPt.class, features);
    }

}
