package com.falabella.mdwcorp.osb.wsdl.cmr.corp.satif.tarjeta.consultaridclientepan.consulta_v1_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-07-13T19:38:49.381-04:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://mdwcorp.falabella.com/OSB/wsdl/CMR/CORP/Satif/tarjeta/consultarIDClientePAN/consulta-v1.0", name = "ConsultarIDClientePANPt")
@XmlSeeAlso({org.xmlsoap.schemas.soap.envelope.ObjectFactory.class, com.falabella.mdwcorp.schema.cmr.tarjeta.v2012.ObjectFactory.class, com.falabella.mdwcorp.osb.schema.cmr.corp.tarjeta.consultaridclientepan.req_v2012.ObjectFactory.class, com.falabella.mdwcorp.schema.cmr.cliente.v2012.ObjectFactory.class, com.falabella.mdwcorp.osb.schema.cmr.corp.tarjeta.consultaridclientepan.resp_v2012.ObjectFactory.class, com.falabella.mdwcorp.common.schema.clientservice.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ConsultarIDClientePANPt {

    @WebResult(name = "consultarIDClientePANResponse", targetNamespace = "http://mdwcorp.falabella.com/OSB/schema/CMR/CORP/tarjeta/consultarIDClientePAN/Resp-v2012.08", partName = "ClienteRespParam")
    @WebMethod(operationName = "ConsultaIDClientePANOp", action = "http://mdwcorp.falabella.com/OSB/wsdl/CMR/CORP/Satif/tarjeta/consultarIDClientePAN/consulta-v1.0/ConsultaIDClientePAN")
    public com.falabella.mdwcorp.osb.schema.cmr.corp.tarjeta.consultaridclientepan.resp_v2012.ConsultarIDClientePANResponseTYPE consultaIDClientePANOp(
        @WebParam(partName = "ClienteReqParam", name = "consultarIDClientePANRequest", targetNamespace = "http://mdwcorp.falabella.com/OSB/schema/CMR/CORP/tarjeta/consultarIDClientePAN/Req-v2012.08")
        com.falabella.mdwcorp.osb.schema.cmr.corp.tarjeta.consultaridclientepan.req_v2012.ConsultarIDClientePANRequestTYPE clienteReqParam,
        @WebParam(partName = "ClientServiceParam", name = "ClientService", targetNamespace = "http://mdwcorp.falabella.com/common/schema/clientservice", header = true)
        com.falabella.mdwcorp.common.schema.clientservice.ClientServiceTYPE clientServiceParam
    ) throws FaultMsg;
}
