
package com.falabella.mdwcorp.osb.wsdl.cmr.corp.switchriesgo.cliente.validaclave.valida_v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-07-13T01:42:52.299-04:00
 * Generated source version: 2.7.11
 */

@WebFault(name = "Fault", targetNamespace = "http://schemas.xmlsoap.org/soap/envelope/")
public class FaultMsg extends Exception {
    
    private org.xmlsoap.schemas.soap.envelope.Fault fault;

    public FaultMsg() {
        super();
    }
    
    public FaultMsg(String message) {
        super(message);
    }
    
    public FaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public FaultMsg(String message, org.xmlsoap.schemas.soap.envelope.Fault fault) {
        super(message);
        this.fault = fault;
    }

    public FaultMsg(String message, org.xmlsoap.schemas.soap.envelope.Fault fault, Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public org.xmlsoap.schemas.soap.envelope.Fault getFaultInfo() {
        return this.fault;
    }
}
