package com.falabella.mdwcorp.osb.wsdl.cmr.corp.switchriesgo.cliente.validaclave.valida_v1_0;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-07-13T01:42:52.427-04:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "ValidarClaveService", 
                  wsdlLocation = "file:/home/cavallinux/dev/src/sandbox/wsmocks/uniquekey-wsserver/src/main/wsdl/OSB_19_ValidarClave.wsdl",
                  targetNamespace = "http://mdwcorp.falabella.com/OSB/wsdl/CMR/CORP/SwitchRiesgo/cliente/validaClave/valida-v1.0") 
public class ValidarClaveService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://mdwcorp.falabella.com/OSB/wsdl/CMR/CORP/SwitchRiesgo/cliente/validaClave/valida-v1.0", "ValidarClaveService");
    public final static QName ValidarClavePort = new QName("http://mdwcorp.falabella.com/OSB/wsdl/CMR/CORP/SwitchRiesgo/cliente/validaClave/valida-v1.0", "ValidarClavePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/cavallinux/dev/src/sandbox/wsmocks/uniquekey-wsserver/src/main/wsdl/OSB_19_ValidarClave.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ValidarClaveService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/cavallinux/dev/src/sandbox/wsmocks/uniquekey-wsserver/src/main/wsdl/OSB_19_ValidarClave.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ValidarClaveService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ValidarClaveService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ValidarClaveService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ValidarClavePt
     */
    @WebEndpoint(name = "ValidarClavePort")
    public ValidarClavePt getValidarClavePort() {
        return super.getPort(ValidarClavePort, ValidarClavePt.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ValidarClavePt
     */
    @WebEndpoint(name = "ValidarClavePort")
    public ValidarClavePt getValidarClavePort(WebServiceFeature... features) {
        return super.getPort(ValidarClavePort, ValidarClavePt.class, features);
    }

}
