package com.falabella.mdwcorp.osb.wsdl.cmr.corp.switchriesgo.cliente.validaclave.valida_v1_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-07-13T01:42:52.349-04:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://mdwcorp.falabella.com/OSB/wsdl/CMR/CORP/SwitchRiesgo/cliente/validaClave/valida-v1.0", name = "ValidarClavePt")
@XmlSeeAlso({org.xmlsoap.schemas.soap.envelope.ObjectFactory.class, com.falabella.mdwcorp.schema.cmr.tarjeta.v2012.ObjectFactory.class, com.falabella.mdwcorp.osb.schema.cmr.corp.cliente.validaclave.resp_v2012.ObjectFactory.class, com.falabella.mdwcorp.osb.schema.cmr.corp.cliente.validaclave.req_v2012.ObjectFactory.class, com.falabella.mdwcorp.schema.cmr.cliente.v2012.ObjectFactory.class, com.falabella.mdwcorp.schema.cmr.clave.v2012.ObjectFactory.class, com.falabella.mdwcorp.common.schema.clientservice.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ValidarClavePt {

    @WebResult(name = "ValidarClaveResponse", targetNamespace = "http://mdwcorp.falabella.com/OSB/schema/CMR/CORP/cliente/validaClave/Resp-v2012.06", partName = "ClaveRespParam")
    @WebMethod(operationName = "ValidaClaveOp", action = "http://mdwcorp.falabella.com/OSB/wsdl/CMR/CORP/SwitchRiesgo/cliente/validaClave/valida-v1.0/ValidaClave")
    public com.falabella.mdwcorp.osb.schema.cmr.corp.cliente.validaclave.resp_v2012.ValidarClaveResponseTYPE validaClaveOp(
        @WebParam(partName = "ClaveReqParam", name = "ValidarClaveRequest", targetNamespace = "http://mdwcorp.falabella.com/OSB/schema/CMR/CORP/cliente/validaClave/Req-v2012.06")
        com.falabella.mdwcorp.osb.schema.cmr.corp.cliente.validaclave.req_v2012.ValidarClaveRequestTYPE claveReqParam,
        @WebParam(partName = "ClientServiceParam", name = "ClientService", targetNamespace = "http://mdwcorp.falabella.com/common/schema/clientservice", header = true)
        com.falabella.mdwcorp.common.schema.clientservice.ClientServiceTYPE clientServiceParam
    ) throws FaultMsg;
}
