package cl.taisachile.scc.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-07-13T17:39:01.290-04:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://ws.scc.taisachile.cl/", name = "Administrationv2WS")
@XmlSeeAlso({ObjectFactory.class})
public interface Administrationv2WS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://ws.scc.taisachile.cl/", className = "cl.taisachile.scc.ws.GetUser")
    @WebMethod
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://ws.scc.taisachile.cl/", className = "cl.taisachile.scc.ws.GetUserResponse")
    public cl.taisachile.scc.ws.GetUserResponseVO getUser(
        @WebParam(name = "getUserParam", targetNamespace = "")
        cl.taisachile.scc.ws.GetUserParamVO getUserParam
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAvailableDeviceTypes", targetNamespace = "http://ws.scc.taisachile.cl/", className = "cl.taisachile.scc.ws.GetAvailableDeviceTypes")
    @WebMethod
    @ResponseWrapper(localName = "getAvailableDeviceTypesResponse", targetNamespace = "http://ws.scc.taisachile.cl/", className = "cl.taisachile.scc.ws.GetAvailableDeviceTypesResponse")
    public cl.taisachile.scc.ws.GetAvailableDeviceTypesResponseVO getAvailableDeviceTypes(
        @WebParam(name = "params", targetNamespace = "")
        cl.taisachile.scc.ws.GetAvailableDeviceTypesParamVO params
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPreferences", targetNamespace = "http://ws.scc.taisachile.cl/", className = "cl.taisachile.scc.ws.GetPreferences")
    @WebMethod
    @ResponseWrapper(localName = "getPreferencesResponse", targetNamespace = "http://ws.scc.taisachile.cl/", className = "cl.taisachile.scc.ws.GetPreferencesResponse")
    public cl.taisachile.scc.ws.GetPreferencesResponseVO getPreferences(
        @WebParam(name = "getPreferencesParam", targetNamespace = "")
        cl.taisachile.scc.ws.GetPreferencesParamVO getPreferencesParam
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "setAuthenticationPreference", targetNamespace = "http://ws.scc.taisachile.cl/", className = "cl.taisachile.scc.ws.SetAuthenticationPreference")
    @WebMethod
    @ResponseWrapper(localName = "setAuthenticationPreferenceResponse", targetNamespace = "http://ws.scc.taisachile.cl/", className = "cl.taisachile.scc.ws.SetAuthenticationPreferenceResponse")
    public cl.taisachile.scc.ws.SetAuthenticationPreferenceResponseVO setAuthenticationPreference(
        @WebParam(name = "params", targetNamespace = "")
        cl.taisachile.scc.ws.SetAuthenticationPreferenceParamVO params
    );
}
