package com.falabella.mdwcorp.osb.wsdl.fif.corp.cliente.identidad.validar_v1_0;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-09-10T15:48:26.782-03:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "ClienteIdentidadValidarService", 
                  wsdlLocation = "file:/home/cavallinux/dev/src/falabella/falabella-ws-mocks/clienteidentidadvalidar-wsserver/src/main/wsdl/OSB_Cliente_Identidad_Validar.wsdl",
                  targetNamespace = "http://mdwcorp.falabella.com/OSB/wsdl/FIF/CORP/cliente/identidad/validar-v1.0") 
public class ClienteIdentidadValidarService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://mdwcorp.falabella.com/OSB/wsdl/FIF/CORP/cliente/identidad/validar-v1.0", "ClienteIdentidadValidarService");
    public final static QName ClienteIdentidadValidarPort = new QName("http://mdwcorp.falabella.com/OSB/wsdl/FIF/CORP/cliente/identidad/validar-v1.0", "ClienteIdentidadValidarPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/cavallinux/dev/src/falabella/falabella-ws-mocks/clienteidentidadvalidar-wsserver/src/main/wsdl/OSB_Cliente_Identidad_Validar.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ClienteIdentidadValidarService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/cavallinux/dev/src/falabella/falabella-ws-mocks/clienteidentidadvalidar-wsserver/src/main/wsdl/OSB_Cliente_Identidad_Validar.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ClienteIdentidadValidarService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ClienteIdentidadValidarService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClienteIdentidadValidarService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ClienteIdentidadValidarPt
     */
    @WebEndpoint(name = "ClienteIdentidadValidarPort")
    public ClienteIdentidadValidarPt getClienteIdentidadValidarPort() {
        return super.getPort(ClienteIdentidadValidarPort, ClienteIdentidadValidarPt.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClienteIdentidadValidarPt
     */
    @WebEndpoint(name = "ClienteIdentidadValidarPort")
    public ClienteIdentidadValidarPt getClienteIdentidadValidarPort(WebServiceFeature... features) {
        return super.getPort(ClienteIdentidadValidarPort, ClienteIdentidadValidarPt.class, features);
    }

}
