package cl.taisachile.scc.ws.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import cl.taisachile.scc.ws.AuthenticationWS;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-07-13T16:27:42.839-04:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "AuthenticationWSImplService", 
                  wsdlLocation = "file:/home/cavallinux/dev/src/sandbox/wsmocks/auth-wsserver/src/main/wsdl/AuthenticationWS.wsdl",
                  targetNamespace = "http://impl.ws.scc.taisachile.cl/") 
public class AuthenticationWSImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.scc.taisachile.cl/", "AuthenticationWSImplService");
    public final static QName AuthenticationWSImplPort = new QName("http://impl.ws.scc.taisachile.cl/", "AuthenticationWSImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/cavallinux/dev/src/sandbox/wsmocks/auth-wsserver/src/main/wsdl/AuthenticationWS.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AuthenticationWSImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/cavallinux/dev/src/sandbox/wsmocks/auth-wsserver/src/main/wsdl/AuthenticationWS.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AuthenticationWSImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AuthenticationWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthenticationWSImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns AuthenticationWS
     */
    @WebEndpoint(name = "AuthenticationWSImplPort")
    public AuthenticationWS getAuthenticationWSImplPort() {
        return super.getPort(AuthenticationWSImplPort, AuthenticationWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthenticationWS
     */
    @WebEndpoint(name = "AuthenticationWSImplPort")
    public AuthenticationWS getAuthenticationWSImplPort(WebServiceFeature... features) {
        return super.getPort(AuthenticationWSImplPort, AuthenticationWS.class, features);
    }

}
