package com.falabella.mdwcorp.osb.wsdl.cmr.cl.cliente.validartoken_v1_0;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-07-13T01:00:50.360-04:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "ValidarTokenService", 
                  wsdlLocation = "file:/home/cavallinux/dev/src/sandbox/wsmocks/validatetoken-wsserver/src/main/wsdl/OSB_CMR_CL_ValidarToken.wsdl",
                  targetNamespace = "http://mdwcorp.falabella.com/OSB/wsdl/CMR/CL/Cliente/ValidarToken-v1.0") 
public class ValidarTokenService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://mdwcorp.falabella.com/OSB/wsdl/CMR/CL/Cliente/ValidarToken-v1.0", "ValidarTokenService");
    public final static QName ValidarTokenPort = new QName("http://mdwcorp.falabella.com/OSB/wsdl/CMR/CL/Cliente/ValidarToken-v1.0", "ValidarTokenPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/cavallinux/dev/src/sandbox/wsmocks/validatetoken-wsserver/src/main/wsdl/OSB_CMR_CL_ValidarToken.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ValidarTokenService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/cavallinux/dev/src/sandbox/wsmocks/validatetoken-wsserver/src/main/wsdl/OSB_CMR_CL_ValidarToken.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ValidarTokenService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ValidarTokenService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ValidarTokenService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ValidarTokenPt
     */
    @WebEndpoint(name = "ValidarTokenPort")
    public ValidarTokenPt getValidarTokenPort() {
        return super.getPort(ValidarTokenPort, ValidarTokenPt.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ValidarTokenPt
     */
    @WebEndpoint(name = "ValidarTokenPort")
    public ValidarTokenPt getValidarTokenPort(WebServiceFeature... features) {
        return super.getPort(ValidarTokenPort, ValidarTokenPt.class, features);
    }

}
