package com.falabella.mdwcorp.osb.wsdl.cmr.cl.cliente.validartoken_v1_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-07-13T01:00:50.321-04:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://mdwcorp.falabella.com/OSB/wsdl/CMR/CL/Cliente/ValidarToken-v1.0", name = "ValidarTokenPt")
@XmlSeeAlso({org.xmlsoap.schemas.soap.envelope.ObjectFactory.class, com.falabella.mdwcorp.osb.schema.cmr.cl.cliente.validartoken.resp_v2014.ObjectFactory.class, com.falabella.mdwcorp.osb.schema.cmr.cl.cliente.validartoken.req_v2014.ObjectFactory.class, com.falabella.mdwcorp.common.schema.clientservice.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ValidarTokenPt {

    @WebResult(name = "validarTokenResponseExp", targetNamespace = "http://mdwcorp.falabella.com/OSB/schema/CMR/CL/Cliente/ValidarToken/Resp-v2014.6", partName = "parameters")
    @WebMethod(action = "http://mdwcorp.falabella.com/OSB/wsdl/CMR/CL/Cliente/ValidarToken-v1.0/ValidarToken")
    public com.falabella.mdwcorp.osb.schema.cmr.cl.cliente.validartoken.resp_v2014.ValidarTokenResponseExp validarTokenOp(
        @WebParam(partName = "parameters", name = "validarTokenRequestExp", targetNamespace = "http://mdwcorp.falabella.com/OSB/schema/CMR/CL/Cliente/ValidarToken/Req-v2014.6")
        com.falabella.mdwcorp.osb.schema.cmr.cl.cliente.validartoken.req_v2014.ValidarTokenRequestExp parameters,
        @WebParam(partName = "ClientServiceParam", name = "ClientService", targetNamespace = "http://mdwcorp.falabella.com/common/schema/clientservice", header = true)
        com.falabella.mdwcorp.common.schema.clientservice.ClientServiceTYPE clientServiceParam
    ) throws FaultMsg;
}
