package com.falabella.ws.service.guardarequerimiento;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2016-03-15T12:14:31.872-03:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://com/adaptus/ws/controladores", name = "WSGuardaRequerimientoWF")
@XmlSeeAlso({ObjectFactory.class})
public interface WSGuardaRequerimientoWF {

    @WebResult(name = "return", targetNamespace = "http://com/adaptus/ws/controladores")
    @RequestWrapper(localName = "RequerimientoWF", targetNamespace = "http://com/adaptus/ws/controladores", className = "com.falabella.ws.service.guardarequerimiento.RequerimientoWF")
    @WebMethod(operationName = "RequerimientoWF")
    @ResponseWrapper(localName = "RequerimientoWFResponse", targetNamespace = "http://com/adaptus/ws/controladores", className = "com.falabella.ws.service.guardarequerimiento.RequerimientoWFResponse")
    public java.lang.String requerimientoWF(
        @WebParam(name = "RUT", targetNamespace = "http://com/adaptus/ws/controladores")
        java.lang.String rut,
        @WebParam(name = "NOMBRES", targetNamespace = "http://com/adaptus/ws/controladores")
        java.lang.String nombres,
        @WebParam(name = "APELLIDO_PATERNO", targetNamespace = "http://com/adaptus/ws/controladores")
        java.lang.String apellidoPATERNO,
        @WebParam(name = "APELLIDO_MATERNO", targetNamespace = "http://com/adaptus/ws/controladores")
        java.lang.String apellidoMATERNO,
        @WebParam(name = "TELEFONO_PARTICULAR", targetNamespace = "http://com/adaptus/ws/controladores")
        java.lang.String telefonoPARTICULAR,
        @WebParam(name = "CELULAR", targetNamespace = "http://com/adaptus/ws/controladores")
        java.lang.String celular,
        @WebParam(name = "DESC_CIUDAD", targetNamespace = "http://com/adaptus/ws/controladores")
        java.lang.String descCIUDAD,
        @WebParam(name = "COD_CIUDAD", targetNamespace = "http://com/adaptus/ws/controladores")
        java.lang.String codCIUDAD,
        @WebParam(name = "MAIL", targetNamespace = "http://com/adaptus/ws/controladores")
        java.lang.String mail,
        @WebParam(name = "TIPO_REQUERIMIENTO", targetNamespace = "http://com/adaptus/ws/controladores")
        java.lang.String tipoREQUERIMIENTO,
        @WebParam(name = "CONCEPTO", targetNamespace = "http://com/adaptus/ws/controladores")
        java.lang.String concepto,
        @WebParam(name = "PRODUCTO", targetNamespace = "http://com/adaptus/ws/controladores")
        java.lang.String producto,
        @WebParam(name = "TIPO", targetNamespace = "http://com/adaptus/ws/controladores")
        java.lang.String tipo,
        @WebParam(name = "MOTIVO", targetNamespace = "http://com/adaptus/ws/controladores")
        java.lang.String motivo,
        @WebParam(name = "COD_SEGMENTO", targetNamespace = "http://com/adaptus/ws/controladores")
        java.lang.String codSEGMENTO,
        @WebParam(name = "AREA_INGRESO", targetNamespace = "http://com/adaptus/ws/controladores")
        java.lang.String areaINGRESO,
        @WebParam(name = "COD_OFICINA", targetNamespace = "http://com/adaptus/ws/controladores")
        java.lang.String codOFICINA,
        @WebParam(name = "ORIGINADOR", targetNamespace = "http://com/adaptus/ws/controladores")
        java.lang.String originador,
        @WebParam(name = "TIPO_FORMULARIO", targetNamespace = "http://com/adaptus/ws/controladores")
        java.lang.String tipoFORMULARIO,
        @WebParam(name = "COMENTARIOS", targetNamespace = "http://com/adaptus/ws/controladores")
        java.lang.String comentarios,
        @WebParam(name = "MALA_ATENCION", targetNamespace = "http://com/adaptus/ws/controladores")
        java.lang.String malaATENCION,
        @WebParam(name = "EJEC_MALA_ATENCION", targetNamespace = "http://com/adaptus/ws/controladores")
        java.lang.String ejecMALAATENCION,
        @WebParam(name = "SUC_MALA_ATENCION", targetNamespace = "http://com/adaptus/ws/controladores")
        java.lang.String sucMALAATENCION,
        @WebParam(name = "EJEC_SOL_PGO", targetNamespace = "http://com/adaptus/ws/controladores")
        java.lang.String ejecSOLPGO
    );
}
