package com.falabella.ws.service.guardarequerimiento;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2016-03-15T12:14:31.981-03:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "WSGuardaRequerimientoWFService", 
                  wsdlLocation = "file:/home/cavallinux/dev/src/falabella/falabella-ws-mocks/guardarequerimientowf-wsserver/src/main/wsdl/WSGuardaRequerimientoWF.wsdl",
                  targetNamespace = "http://com/adaptus/ws/controladores") 
public class WSGuardaRequerimientoWFService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://com/adaptus/ws/controladores", "WSGuardaRequerimientoWFService");
    public final static QName WSGuardaRequerimientoWFSoapPort = new QName("http://com/adaptus/ws/controladores", "WSGuardaRequerimientoWFSoapPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/cavallinux/dev/src/falabella/falabella-ws-mocks/guardarequerimientowf-wsserver/src/main/wsdl/WSGuardaRequerimientoWF.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WSGuardaRequerimientoWFService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/cavallinux/dev/src/falabella/falabella-ws-mocks/guardarequerimientowf-wsserver/src/main/wsdl/WSGuardaRequerimientoWF.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WSGuardaRequerimientoWFService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSGuardaRequerimientoWFService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSGuardaRequerimientoWFService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns WSGuardaRequerimientoWF
     */
    @WebEndpoint(name = "WSGuardaRequerimientoWFSoapPort")
    public WSGuardaRequerimientoWF getWSGuardaRequerimientoWFSoapPort() {
        return super.getPort(WSGuardaRequerimientoWFSoapPort, WSGuardaRequerimientoWF.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSGuardaRequerimientoWF
     */
    @WebEndpoint(name = "WSGuardaRequerimientoWFSoapPort")
    public WSGuardaRequerimientoWF getWSGuardaRequerimientoWFSoapPort(WebServiceFeature... features) {
        return super.getPort(WSGuardaRequerimientoWFSoapPort, WSGuardaRequerimientoWF.class, features);
    }

}
