package com.falabella.ws.service.aumentocupo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2016-03-11T16:33:19.674-03:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "AumentoCupoService", 
                  wsdlLocation = "file:/home/cavallinux/dev/src/falabella/falabella-ws-mocks/aumentocupo-wsserver/src/main/wsdl/AumentoCupoPort.wsdl",
                  targetNamespace = "http://impl.ws.aumentocupo.trebolit.com/") 
public class AumentoCupoService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.aumentocupo.trebolit.com/", "AumentoCupoService");
    public final static QName AumentoCupoPort = new QName("http://impl.ws.aumentocupo.trebolit.com/", "AumentoCupoPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/cavallinux/dev/src/falabella/falabella-ws-mocks/aumentocupo-wsserver/src/main/wsdl/AumentoCupoPort.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AumentoCupoService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/cavallinux/dev/src/falabella/falabella-ws-mocks/aumentocupo-wsserver/src/main/wsdl/AumentoCupoPort.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AumentoCupoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AumentoCupoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AumentoCupoService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns AumentoCupoImpl
     */
    @WebEndpoint(name = "AumentoCupoPort")
    public AumentoCupoImpl getAumentoCupoPort() {
        return super.getPort(AumentoCupoPort, AumentoCupoImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AumentoCupoImpl
     */
    @WebEndpoint(name = "AumentoCupoPort")
    public AumentoCupoImpl getAumentoCupoPort(WebServiceFeature... features) {
        return super.getPort(AumentoCupoPort, AumentoCupoImpl.class, features);
    }

}
