package com.falabella.ws.service.aumentocupo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2016-03-11T16:33:19.566-03:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://impl.ws.aumentocupo.trebolit.com/", name = "AumentoCupoImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface AumentoCupoImpl {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "aplicarAumentoCupoLC", targetNamespace = "http://impl.ws.aumentocupo.trebolit.com/", className = "com.falabella.ws.service.aumentocupo.AplicarAumentoCupoLC")
    @WebMethod
    @ResponseWrapper(localName = "aplicarAumentoCupoLCResponse", targetNamespace = "http://impl.ws.aumentocupo.trebolit.com/", className = "com.falabella.ws.service.aumentocupo.AplicarAumentoCupoLCResponse")
    public com.falabella.ws.service.aumentocupo.RespuestaVO aplicarAumentoCupoLC(
        @WebParam(name = "rut", targetNamespace = "")
        java.lang.Integer rut,
        @WebParam(name = "numeroCuenta", targetNamespace = "")
        java.lang.Double numeroCuenta,
        @WebParam(name = "sucursal", targetNamespace = "")
        java.lang.Short sucursal,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.Integer usuario,
        @WebParam(name = "monto", targetNamespace = "")
        java.lang.Double monto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "aplicarAumentoCupoTC", targetNamespace = "http://impl.ws.aumentocupo.trebolit.com/", className = "com.falabella.ws.service.aumentocupo.AplicarAumentoCupoTC")
    @WebMethod
    @ResponseWrapper(localName = "aplicarAumentoCupoTCResponse", targetNamespace = "http://impl.ws.aumentocupo.trebolit.com/", className = "com.falabella.ws.service.aumentocupo.AplicarAumentoCupoTCResponse")
    public com.falabella.ws.service.aumentocupo.RespuestaVO aplicarAumentoCupoTC(
        @WebParam(name = "rut", targetNamespace = "")
        java.lang.Integer rut,
        @WebParam(name = "numeroTarjeta", targetNamespace = "")
        java.lang.String numeroTarjeta,
        @WebParam(name = "sucursal", targetNamespace = "")
        java.lang.Short sucursal,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.Integer usuario,
        @WebParam(name = "cupoOtorgado", targetNamespace = "")
        java.lang.Double cupoOtorgado,
        @WebParam(name = "cupoActual", targetNamespace = "")
        java.lang.Double cupoActual,
        @WebParam(name = "flagDolar", targetNamespace = "")
        java.lang.String flagDolar
    );
}
