package cl.taisa.scc.ws.adminv2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-05-14T09:50:26.896-04:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://ws.scc.taisachile.cl/", name = "Administrationv2WS")
@XmlSeeAlso({ObjectFactory.class})
public interface Administrationv2WS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://ws.scc.taisachile.cl/", className = "cl.taisa.scc.ws.adminv2.GetUser")
    @WebMethod
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://ws.scc.taisachile.cl/", className = "cl.taisa.scc.ws.adminv2.GetUserResponse")
    public cl.taisa.scc.ws.adminv2.GetUserResponseVO getUser(
        @WebParam(name = "getUserParam", targetNamespace = "")
        cl.taisa.scc.ws.adminv2.GetUserParamVO getUserParam
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAvailableDeviceTypes", targetNamespace = "http://ws.scc.taisachile.cl/", className = "cl.taisa.scc.ws.adminv2.GetAvailableDeviceTypes")
    @WebMethod
    @ResponseWrapper(localName = "getAvailableDeviceTypesResponse", targetNamespace = "http://ws.scc.taisachile.cl/", className = "cl.taisa.scc.ws.adminv2.GetAvailableDeviceTypesResponse")
    public cl.taisa.scc.ws.adminv2.GetAvailableDeviceTypesResponseVO getAvailableDeviceTypes(
        @WebParam(name = "params", targetNamespace = "")
        cl.taisa.scc.ws.adminv2.GetAvailableDeviceTypesParamVO params
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPreferences", targetNamespace = "http://ws.scc.taisachile.cl/", className = "cl.taisa.scc.ws.adminv2.GetPreferences")
    @WebMethod
    @ResponseWrapper(localName = "getPreferencesResponse", targetNamespace = "http://ws.scc.taisachile.cl/", className = "cl.taisa.scc.ws.adminv2.GetPreferencesResponse")
    public cl.taisa.scc.ws.adminv2.GetPreferencesResponseVO getPreferences(
        @WebParam(name = "getPreferencesParam", targetNamespace = "")
        cl.taisa.scc.ws.adminv2.GetPreferencesParamVO getPreferencesParam
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "setAuthenticationPreference", targetNamespace = "http://ws.scc.taisachile.cl/", className = "cl.taisa.scc.ws.adminv2.SetAuthenticationPreference")
    @WebMethod
    @ResponseWrapper(localName = "setAuthenticationPreferenceResponse", targetNamespace = "http://ws.scc.taisachile.cl/", className = "cl.taisa.scc.ws.adminv2.SetAuthenticationPreferenceResponse")
    public cl.taisa.scc.ws.adminv2.SetAuthenticationPreferenceResponseVO setAuthenticationPreference(
        @WebParam(name = "params", targetNamespace = "")
        cl.taisa.scc.ws.adminv2.SetAuthenticationPreferenceParamVO params
    );
}
