package cl.taisa.scc.ws.adminv2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-05-14T09:50:26.942-04:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "Administrationv2WSImplService", 
                  wsdlLocation = "file:/home/cavallinux/dev/src/falabella/falabella-ws-mocks/adminv2-wsserver/src/main/wsdl/Administrationv2WS_1.wsdl",
                  targetNamespace = "http://impl.ws.scc.taisachile.cl/") 
public class Administrationv2WSImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.scc.taisachile.cl/", "Administrationv2WSImplService");
    public final static QName Administrationv2WSImplPort = new QName("http://impl.ws.scc.taisachile.cl/", "Administrationv2WSImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/cavallinux/dev/src/falabella/falabella-ws-mocks/adminv2-wsserver/src/main/wsdl/Administrationv2WS_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Administrationv2WSImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/cavallinux/dev/src/falabella/falabella-ws-mocks/adminv2-wsserver/src/main/wsdl/Administrationv2WS_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Administrationv2WSImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Administrationv2WSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Administrationv2WSImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns Administrationv2WS
     */
    @WebEndpoint(name = "Administrationv2WSImplPort")
    public Administrationv2WS getAdministrationv2WSImplPort() {
        return super.getPort(Administrationv2WSImplPort, Administrationv2WS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Administrationv2WS
     */
    @WebEndpoint(name = "Administrationv2WSImplPort")
    public Administrationv2WS getAdministrationv2WSImplPort(WebServiceFeature... features) {
        return super.getPort(Administrationv2WSImplPort, Administrationv2WS.class, features);
    }

}
