package com.falabella.mdwcorp.osb.wsdl.fif.corp.cliente.identidad.validar_v1_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-09-10T16:38:09.574-03:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://mdwcorp.falabella.com/OSB/wsdl/FIF/CORP/cliente/identidad/validar-v1.0", name = "ClienteIdentidadValidarPt")
@XmlSeeAlso({org.xmlsoap.schemas.soap.envelope.ObjectFactory.class, com.falabella.mdwcorp.osb.schema.fif.corp.cliente.identidad.validar.req_v2015.ObjectFactory.class, com.falabella.mdwcorp.osb.schema.fif.corp.cliente.identidad.validar.resp_v2015.ObjectFactory.class, com.falabella.mdwcorp.common.schema.clientservice.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ClienteIdentidadValidarPt {

    @WebResult(name = "clienteIdentidadValidarExpResp", targetNamespace = "http://mdwcorp.falabella.com/OSB/schema/FIF/CORP/cliente/identidad/validar/Resp-v2015.08", partName = "ClienteIdentidadValidarRespParam")
    @WebMethod(operationName = "ClienteIdentidadValidarOp", action = "http://mdwcorp.falabella.com/OSB/wsdl/FIF/CORP/cliente/identidad/validar-v1.0/Op")
    public com.falabella.mdwcorp.osb.schema.fif.corp.cliente.identidad.validar.resp_v2015.ClienteIdentidadValidarExpRespTYPE clienteIdentidadValidarOp(
        @WebParam(partName = "ClienteIdentidadValidarReqParam", name = "clienteIdentidadValidarExpReq", targetNamespace = "http://mdwcorp.falabella.com/OSB/schema/FIF/CORP/cliente/identidad/validar/Req-v2015.08")
        com.falabella.mdwcorp.osb.schema.fif.corp.cliente.identidad.validar.req_v2015.ClienteIdentidadValidarExpReqTYPE clienteIdentidadValidarReqParam,
        @WebParam(partName = "ClientServiceParam", name = "ClientService", targetNamespace = "http://mdwcorp.falabella.com/common/schema/clientservice", header = true)
        com.falabella.mdwcorp.common.schema.clientservice.ClientServiceTYPE clientServiceParam
    ) throws FaultMsg;
}
