package cl.taisachile.scc.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-07-13T16:27:42.765-04:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://ws.scc.taisachile.cl/", name = "AuthenticationWS")
@XmlSeeAlso({ObjectFactory.class})
public interface AuthenticationWS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getChallenge", targetNamespace = "http://ws.scc.taisachile.cl/", className = "cl.taisachile.scc.ws.GetChallenge")
    @WebMethod
    @ResponseWrapper(localName = "getChallengeResponse", targetNamespace = "http://ws.scc.taisachile.cl/", className = "cl.taisachile.scc.ws.GetChallengeResponse")
    public cl.taisachile.scc.ws.GetChallengeResponseVO getChallenge(
        @WebParam(name = "getChallengeParam", targetNamespace = "")
        cl.taisachile.scc.ws.GetChallengeParamVO getChallengeParam
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "authenticateOTPCorp", targetNamespace = "http://ws.scc.taisachile.cl/", className = "cl.taisachile.scc.ws.AuthenticateOTPCorp")
    @WebMethod
    @ResponseWrapper(localName = "authenticateOTPCorpResponse", targetNamespace = "http://ws.scc.taisachile.cl/", className = "cl.taisachile.scc.ws.AuthenticateOTPCorpResponse")
    public cl.taisachile.scc.ws.AuthenticateResponseVO authenticateOTPCorp(
        @WebParam(name = "authenticateOTPCorpParam", targetNamespace = "")
        cl.taisachile.scc.ws.AuthenticateOTPParamVO authenticateOTPCorpParam
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "authenticateCU", targetNamespace = "http://ws.scc.taisachile.cl/", className = "cl.taisachile.scc.ws.AuthenticateCU")
    @WebMethod
    @ResponseWrapper(localName = "authenticateCUResponse", targetNamespace = "http://ws.scc.taisachile.cl/", className = "cl.taisachile.scc.ws.AuthenticateCUResponse")
    public cl.taisachile.scc.ws.AuthenticateResponseCUVO authenticateCU(
        @WebParam(name = "authenticateParam", targetNamespace = "")
        cl.taisachile.scc.ws.AuthenticateParamVO authenticateParam
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getChallengeOTP", targetNamespace = "http://ws.scc.taisachile.cl/", className = "cl.taisachile.scc.ws.GetChallengeOTP")
    @WebMethod
    @ResponseWrapper(localName = "getChallengeOTPResponse", targetNamespace = "http://ws.scc.taisachile.cl/", className = "cl.taisachile.scc.ws.GetChallengeOTPResponse")
    public cl.taisachile.scc.ws.GetChallengeResponseVO getChallengeOTP(
        @WebParam(name = "getChallengeParamOTP", targetNamespace = "")
        cl.taisachile.scc.ws.GetChallengeOTPParamVO getChallengeParamOTP
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getChallengeOTPCorp", targetNamespace = "http://ws.scc.taisachile.cl/", className = "cl.taisachile.scc.ws.GetChallengeOTPCorp")
    @WebMethod
    @ResponseWrapper(localName = "getChallengeOTPCorpResponse", targetNamespace = "http://ws.scc.taisachile.cl/", className = "cl.taisachile.scc.ws.GetChallengeOTPCorpResponse")
    public cl.taisachile.scc.ws.GetChallengeResponseVO getChallengeOTPCorp(
        @WebParam(name = "getChallengeParamOTPCorp", targetNamespace = "")
        cl.taisachile.scc.ws.GetChallengeOTPParamVO getChallengeParamOTPCorp
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "authenticate", targetNamespace = "http://ws.scc.taisachile.cl/", className = "cl.taisachile.scc.ws.Authenticate")
    @WebMethod
    @ResponseWrapper(localName = "authenticateResponse", targetNamespace = "http://ws.scc.taisachile.cl/", className = "cl.taisachile.scc.ws.AuthenticateResponse")
    public cl.taisachile.scc.ws.AuthenticateResponseVO authenticate(
        @WebParam(name = "authenticateParam", targetNamespace = "")
        cl.taisachile.scc.ws.AuthenticateParamVO authenticateParam
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "authenticateOTP", targetNamespace = "http://ws.scc.taisachile.cl/", className = "cl.taisachile.scc.ws.AuthenticateOTP")
    @WebMethod
    @ResponseWrapper(localName = "authenticateOTPResponse", targetNamespace = "http://ws.scc.taisachile.cl/", className = "cl.taisachile.scc.ws.AuthenticateOTPResponse")
    public cl.taisachile.scc.ws.AuthenticateResponseVO authenticateOTP(
        @WebParam(name = "authenticateOTPParam", targetNamespace = "")
        cl.taisachile.scc.ws.AuthenticateOTPParamVO authenticateOTPParam
    );
}
