
package com.falabella.ws.service.cliclienteconsolidado;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.11
 * 2016-03-17T19:17:21.365-03:00
 * Generated source version: 2.7.11
 */

@WebFault(name = "BancoFalabellaException", targetNamespace = "java:cl.bancofalabella.ebanking.exception")
public class BancoFalabellaException_Exception extends Exception {
    
    private com.falabella.ws.service.cliclienteconsolidado.BancoFalabellaException bancoFalabellaException;

    public BancoFalabellaException_Exception() {
        super();
    }
    
    public BancoFalabellaException_Exception(String message) {
        super(message);
    }
    
    public BancoFalabellaException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public BancoFalabellaException_Exception(String message, com.falabella.ws.service.cliclienteconsolidado.BancoFalabellaException bancoFalabellaException) {
        super(message);
        this.bancoFalabellaException = bancoFalabellaException;
    }

    public BancoFalabellaException_Exception(String message, com.falabella.ws.service.cliclienteconsolidado.BancoFalabellaException bancoFalabellaException, Throwable cause) {
        super(message, cause);
        this.bancoFalabellaException = bancoFalabellaException;
    }

    public com.falabella.ws.service.cliclienteconsolidado.BancoFalabellaException getFaultInfo() {
        return this.bancoFalabellaException;
    }
}
