package com.falabella.ws.service.cliclienteconsolidado;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2016-03-17T19:17:21.425-03:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "CliClienteConsolidadoService", 
                  wsdlLocation = "http://ebankingcont1.bancofalabella.cl:7010/eBanking/CliClienteConsolidado?wsdl",
                  targetNamespace = "http://cl/bancofalabella/ebanking/service") 
public class CliClienteConsolidadoService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cl/bancofalabella/ebanking/service", "CliClienteConsolidadoService");
    public final static QName CliClienteConsolidadoSoapPort = new QName("http://cl/bancofalabella/ebanking/service", "CliClienteConsolidadoSoapPort");
    static {
        URL url = null;
        try {
            url = new URL("http://ebankingcont1.bancofalabella.cl:7010/eBanking/CliClienteConsolidado?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CliClienteConsolidadoService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://ebankingcont1.bancofalabella.cl:7010/eBanking/CliClienteConsolidado?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CliClienteConsolidadoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CliClienteConsolidadoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CliClienteConsolidadoService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns CliClienteConsolidado
     */
    @WebEndpoint(name = "CliClienteConsolidadoSoapPort")
    public CliClienteConsolidado getCliClienteConsolidadoSoapPort() {
        return super.getPort(CliClienteConsolidadoSoapPort, CliClienteConsolidado.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CliClienteConsolidado
     */
    @WebEndpoint(name = "CliClienteConsolidadoSoapPort")
    public CliClienteConsolidado getCliClienteConsolidadoSoapPort(WebServiceFeature... features) {
        return super.getPort(CliClienteConsolidadoSoapPort, CliClienteConsolidado.class, features);
    }

}
