package com.falabella.ws.service.cliclienteconsolidado;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2016-03-17T19:17:21.398-03:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://cl/bancofalabella/ebanking/service", name = "CliClienteConsolidado")
@XmlSeeAlso({ObjectFactory.class})
public interface CliClienteConsolidado {

    @WebResult(name = "return", targetNamespace = "http://cl/bancofalabella/ebanking/service")
    @RequestWrapper(localName = "CliResumenCon", targetNamespace = "http://cl/bancofalabella/ebanking/service", className = "com.falabella.ws.service.cliclienteconsolidado.CliResumenCon")
    @WebMethod(operationName = "CliResumenCon")
    @ResponseWrapper(localName = "CliResumenConResponse", targetNamespace = "http://cl/bancofalabella/ebanking/service", className = "com.falabella.ws.service.cliclienteconsolidado.CliResumenConResponse")
    public com.falabella.ws.service.cliclienteconsolidado.ArrayOfCliResumenConMsgLiteral cliResumenCon(
        @WebParam(name = "CLI_CLIENTE_RUT", targetNamespace = "http://cl/bancofalabella/ebanking/service")
        long cliCLIENTERUT
    ) throws BancoFalabellaException_Exception;

    @WebResult(name = "return", targetNamespace = "http://cl/bancofalabella/ebanking/service")
    @RequestWrapper(localName = "CliOfertasCliente", targetNamespace = "http://cl/bancofalabella/ebanking/service", className = "com.falabella.ws.service.cliclienteconsolidado.CliOfertasCliente")
    @WebMethod(operationName = "CliOfertasCliente")
    @ResponseWrapper(localName = "CliOfertasClienteResponse", targetNamespace = "http://cl/bancofalabella/ebanking/service", className = "com.falabella.ws.service.cliclienteconsolidado.CliOfertasClienteResponse")
    public com.falabella.ws.service.cliclienteconsolidado.ArrayOfCliOfertasClienteMsgLiteral cliOfertasCliente(
        @WebParam(name = "CLI_CLIENTE_RUT", targetNamespace = "http://cl/bancofalabella/ebanking/service")
        long cliCLIENTERUT,
        @WebParam(name = "CLI_INCLUYE_TODAS_LAS_OFERTAS", targetNamespace = "http://cl/bancofalabella/ebanking/service")
        java.lang.String cliINCLUYETODASLASOFERTAS,
        @WebParam(name = "CLI_INCLUYE_OFERTA_MANTENCION", targetNamespace = "http://cl/bancofalabella/ebanking/service")
        java.lang.String cliINCLUYEOFERTAMANTENCION,
        @WebParam(name = "CLI_INCLUYE_LCC", targetNamespace = "http://cl/bancofalabella/ebanking/service")
        java.lang.String cliINCLUYELCC,
        @WebParam(name = "CLI_INCLUYE_LCD", targetNamespace = "http://cl/bancofalabella/ebanking/service")
        java.lang.String cliINCLUYELCD,
        @WebParam(name = "CLI_INCLUYE_CRC", targetNamespace = "http://cl/bancofalabella/ebanking/service")
        java.lang.String cliINCLUYECRC,
        @WebParam(name = "CLI_INCLUYE_RDD_CONSOLIDACION", targetNamespace = "http://cl/bancofalabella/ebanking/service")
        java.lang.String cliINCLUYERDDCONSOLIDACION,
        @WebParam(name = "CLI_INCLUYE_APERTURA_LCC", targetNamespace = "http://cl/bancofalabella/ebanking/service")
        java.lang.String cliINCLUYEAPERTURALCC,
        @WebParam(name = "CLI_INCLUYE_TCR", targetNamespace = "http://cl/bancofalabella/ebanking/service")
        java.lang.String cliINCLUYETCR
    ) throws BancoFalabellaException_Exception;
}
