package com.falabella.ws.service.evaluacliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-27T13:49:44.447-03:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://control.evaluacionEnlinea.ws.bancofalabella.cl/", name = "ServicioEvalCliente")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ServicioEvalCliente {

    @WebResult(name = "salidaEvaluaCliente", targetNamespace = "http://control.evaluacionEnlinea.ws.bancofalabella.cl/", partName = "parameters")
    @WebMethod(operationName = "EvaGenPondera")
    public SalidaEvaluaCliente evaGenPondera(
        @WebParam(partName = "parameters", name = "entradaEvaluaCliente", targetNamespace = "http://control.evaluacionEnlinea.ws.bancofalabella.cl/")
        EntradaEvaluaCliente parameters
    );
}
