package cl.taisachile.scc.ws.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import cl.taisachile.scc.ws.AdministrationCUWS;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-07-13T14:37:31.060-04:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "AdministrationCUWSImplService", 
                  wsdlLocation = "file:/home/cavallinux/dev/src/sandbox/wsmocks/admincu-wsserver/src/main/wsdl/AdministrationCU.wsdl",
                  targetNamespace = "http://impl.ws.scc.taisachile.cl/") 
public class AdministrationCUWSImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.scc.taisachile.cl/", "AdministrationCUWSImplService");
    public final static QName AdministrationCUWSImplPort = new QName("http://impl.ws.scc.taisachile.cl/", "AdministrationCUWSImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/cavallinux/dev/src/sandbox/wsmocks/admincu-wsserver/src/main/wsdl/AdministrationCU.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AdministrationCUWSImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/cavallinux/dev/src/sandbox/wsmocks/admincu-wsserver/src/main/wsdl/AdministrationCU.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AdministrationCUWSImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AdministrationCUWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdministrationCUWSImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns AdministrationCUWS
     */
    @WebEndpoint(name = "AdministrationCUWSImplPort")
    public AdministrationCUWS getAdministrationCUWSImplPort() {
        return super.getPort(AdministrationCUWSImplPort, AdministrationCUWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdministrationCUWS
     */
    @WebEndpoint(name = "AdministrationCUWSImplPort")
    public AdministrationCUWS getAdministrationCUWSImplPort(WebServiceFeature... features) {
        return super.getPort(AdministrationCUWSImplPort, AdministrationCUWS.class, features);
    }

}
